name: ci

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  code-test:
    name: Run Rspec Tests on Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run Rspec
        run: rspec

  action-test:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test the local action
        uses: ./
        env:
          BRAKEMAN_ARGS: --force-scan
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
